### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by werdna521** [AngSanley/ayam#14] opened 2020-08-14 12:28 UTC
Hi, I am experiencing an issue when I was trying to log into my Bimay account via Ayam today. Each time I tried to log in, the button started loading and never seemed to stop. I can make sure that it is not due to a bad connection or Bimay's server downtime as I was able to log in via [BinusMaya](https://binusmaya.binus.ac.id). Here's what keeps on happening.

![image](https://user-images.githubusercontent.com/48923485/90249064-ff9f9b00-de63-11ea-9fe2-7128a439dadd.png)

**Comment by AngSanley** [comment] 2020-08-14 13:18
I just tried to log in to my account and it does work. Maybe try logging in again?

**Comment by werdna521** [comment] 2020-08-16 17:12
I've tried logging and it's still not working for me.

**Comment by AngSanley** [comment] 2020-08-30 17:31
Can you help debugging this issue?

**Comment by werdna521** [comment] 2020-08-31 16:40
I'm not 100% sure, but I'll give it a try later

**Comment by AngSanley** [comment] 2020-10-04 06:47
Hi, it seems like the problem is solved by itself. Maybe there's a change in Bimay's backend that causes this issue.

I'll close this for now, feel free to reopen again if you found this issue again. Thanks!

**Closed by AngSanley** 2020-10-04 06:47 UTC
